spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nano_banana
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

huggingface:
  api:
    key: ${HF}
    model: black-forest-labs/FLUX.1-schnell

server:
  port: 9091
